name: Release
on:
  # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushbranchestagsbranches-ignoretags-ignore
  push:
    tags:
      - "v*.*.*"

jobs:
  uberjar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Prepare java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@9.5
        with:
          lein: 2.9.8
      - name: Build uberjar
        # https://docs.github.com/en/actions/learn-github-actions/contexts#env-context
        run: |
          export APP_VERSION=$GITHUB_REF_NAME
          export PROJECT_URL=https://github.com/mebble/mcj
          env > .env
          make build
      - name: Release uberjar
        uses: softprops/action-gh-release@v1
        with:
          files: target/mcj.jar
          fail_on_unmatched_files: true
